'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class PV_TEAMCELLEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=PV_TEAMCELLEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Category() As DbSet(Of Category)
    Public Overridable Property City() As DbSet(Of City)
    Public Overridable Property Country() As DbSet(Of Country)
    Public Overridable Property Product() As DbSet(Of Product)
    Public Overridable Property Provider() As DbSet(Of Provider)
    Public Overridable Property Employee() As DbSet(Of Employee)
    Public Overridable Property Users() As DbSet(Of Users)

End Class
