'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Employee
    Public Property IdEmployee As Integer
    Public Property FirstName As String
    Public Property SecondName As String
    Public Property FirstSurname As String
    Public Property SecondSurname As String
    Public Property BirthDay As Nullable(Of Date)
    Public Property IdentificationCard As String
    Public Property State As String
    Public Property Status As Nullable(Of Boolean)

    Public Overridable Property Users As ICollection(Of Users) = New HashSet(Of Users)

End Class
