'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product
    Public Property IdProduct As Integer
    Public Property Name As String
    Public Property IdProvider As Nullable(Of Integer)
    Public Property IdCategory As Nullable(Of Integer)
    Public Property costing As String
    Public Property Description As String
    Public Property Estatus As Nullable(Of Boolean)

    Public Overridable Property Category As Category
    Public Overridable Property Provider As Provider

End Class
