'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Provider
    Public Property IdProvider As Integer
    Public Property Name As String
    Public Property IdCity As Nullable(Of Integer)
    Public Property Address As String
    Public Property Estatus As Nullable(Of Boolean)

    Public Overridable Property City As City
    Public Overridable Property Product As ICollection(Of Product) = New HashSet(Of Product)

End Class
