'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Users
    Public Property IdUser As Integer
    Public Property UserName As String
    Public Property Salt As Byte()
    Public Property Password As Byte()
    Public Property IdEmployee As Nullable(Of Integer)
    Public Property Status As Nullable(Of Boolean)

    Public Overridable Property Employee As Employee

End Class
