//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int IdProvider { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdCity { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
